<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "l10nmgr_grid"
 *
 * Auto generated by Extension Builder 2015-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'l10nmgr Grid Extension',
	'description' => 'Extends the l10nmgr for Gridelements Individual FlexForm configuration. Now you can Translate Every Gridelemnts Field from Input-Text to tt_content.',
	'category' => 'module',
	'author' => 'Web-Kon Internetagentur',
	'author_email' => 'technik@web-kon.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
			'l10nmgr' => '7.1.2-8.2.99',
			'gridelements' => '7.1.0-7.1.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
